FROM node:14-alpine AS development

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "start"]

# FROM development AS builder

# RUN npm run build

# FROM nginx:1.16.0-alpine

# COPY --from=builder /app/build /usr/share/nginx/html

# CMD ["nginx", "-g", "daemon off;"]
